# Generated by Django 6.0 on 2025-12-19 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('delayed', 'Delayed'), ('boarding', 'Boarding'), ('departed', 'Departed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20),
        ),
    ]
